// src/utils/token.js

export const token =
  "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X251bWJlciI6IiIsImJyYW5jaF9jb2RlIjoiIiwiY2lmIjoiIiwiZXhwIjoxNzUyNTAwOTIxLCJwaG9uZV9udW1iZXIiOiIyNTQ3NDUxOTI5MTMiLCJyb2xlX2lkIjpbMV0sInVzZXJfaWQiOjEsInVzZXJfdHlwZSI6ImFkbWluIiwidXNlcm5hbWUiOiJhZG1pbiJ9.1_ItFb8AfAJVGZ7WTOASyVc7ozOREkcq7WVq62JrFl4";
